name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MiTV-Key-Mapper
          path: app/build/outputs/apk/release/*.apk

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: MiTV-Key-Mapper

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-release.apk
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: |
            Android TV Key Mapper for Xiaomi Mi Box 4
            
            ### Changes
            Auto-generated release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
